controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    amr_diff_drive_controller:
      type: amr_diff_drive_controller/DiffDriveController

    amr_base_controller:
      type: amr_base_controller/BaseController

    amr_battery_controller:
      type: amr_battery_controller/BatteryController

    amr_gpio_controller:
      type: amr_gpio_controller/GPIOController

    amr_state_controller:
      type: amr_state_controller/StateController

    amr_turn_table_lift_controller:
      type: amr_turn_table_lift_controller/TurnTableLiftController

    joint_state_controller:
      type: joint_state_controller/JointStateController

amr_base_controller:
  ros__parameters:
    button_name: button_joint
    tower_light_name: lamp_joint
    dcu_name: dcu_joint

amr_battery_controller:
  ros__parameters:
    battery_name: battery_joint
    thread_high: 25.5
    thread_low: 23.5
    max_voltage: 27.5
    min_voltage: 23.4

amr_gpio_controller:
  ros__parameters:
    gpio_name: gpio_joint

amr_state_controller:
  ros__parameters:
    simulation: false

amr_turn_table_lift_controller:
  ros__parameters:
    turn_table_lift_name: turn_table_lift_joint
    lift_up_speed: 4 # mm/s
    lift_down_speed: 4 # mm/s

amr_diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation: 0.317
    wheels_per_side: 1 # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.064

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
"amr_low_type_controller.yaml" 97L, 2563B