/**:
  ros__parameters:
    forward_planner:
      update_timer_msec: 100
      linear_profile:
        max_speed: 0.5  # [m/s]
        max_acceleration: 0.3  # [m/s^2]
        max_deceleration: 0.6  # [m/s^2]
        resolution: 0.01  # [m/s]
      angular_profile:
        max_speed: 1.0  # [rad/s]
        max_acceleration: 3.0  # [rad/s^2]
        max_deceleration: 3.0  # [rad/s^2]
        resolution: 0.04  # [rad/s]
      deceleration_for_stop: 0.1  #[m/s^2]
      dense_angular_resolution: 0.04  # [rad/s]
      outdated_input_time_threshold: 1.0
      stuck_time_threshold: 0.5
      forward_safety_distance: 0.4  # [m]
      min_curvature_radius: 0.5
      prediction_time: 2.5
      score_weight:
        goal_distance: 0.15
        forward_clearance: 0.3
      curvature_based:
        use: false
        max_absolute_curvature: 2.0
        curvature_resolution: 0.1
        zero_velocity_threshold: 0.01
      arrival:
        control_based:
          use: true
        error_tolerance: 0.1  # [m]
        min_clearance: 0.2
      stop_and_go:
        min_clearance: 0.2
      back_up:
        use: false
        max_speed: 0.1  # speed, should be positive
        distance: 0.1
        backward_safety_distance: 0.2
      velocity_adjustment:
        max_side_clearance: 0.5
      velocity_regulation:
        side_clearance:
          gain: 3.0
          offset: 0.3
          prediction_time: 0.5
        max_lateral_acceleration: 0.5
      oscillation_prevention:
        reset_time: 1.0
        delta_w_threshold: 0.05
        score_benefit_ratio: 0.05
      enable_scored_velocity_list_visualization: false
    forward_planner_rviz:
      score_list_visualization:
        lowest_score: -0.31
        highest_score: 0.2
    goal_generator:
      update_timer_msec: 100
      lookahead_distance:
        max: 5.0  # [m]
        min: 1.0  # [m]
        adaptive:
          use: true
"motion_planner.yaml" 198L, 5999B                                                                                                                                                                                   1,1           Top
