/**:
  ros__parameters:
    robot:
      shape:
        footprint:
          type: 'rectangle'
          width: 0.7540
          length: 1.2490
          offset: # rectangle center from baselink
            x: 0.0 # [m], forward
            y: 0.0 # [m], left
        height: 1.3485
      motion:
        linear:
          speed_max: 0.5
          acceleration_max: 0.2
          deceleration_max: 0.2
        angular:
          speed_max: 0.5
          acceleration_max: 0.25
          deceleration_max: 0.3
        climbing:
          height_max: 0.05
      odometry:
        min_valid_time_duration: 0.01 # [s], minimum time interval recommended for valid odometry sampling
      sensor: # all metrics: length(m), angle(rad)
        front_depth: # depth camera
          topic: '/bot_sensor/camera_body/depth/image'
          info_topic: '/bot_sensor/camera_body/depth/camera_info'
          intrinsics:
            range: [0.1, 3.0]
          extrinsics:
            xyz: [0.2486, 0.0, 0.1345]
            rpy: [0.0, 0.0, 0.0]
          is_scanning_ground: false
        lidar_front: # spinning lidar
          topic: '/bot_sensor/lidar_front/laser_scan'
          intrinsics:
            range: [0.05, 20.0] # [min, max]
            fov: [0.0, 2.26893, 4.01426, 6.283185307179586] # [from to from to]
          extrinsics:
            xyz: [0.5195, 0.2970, 0.2715]
            yaw: 0.785398163
            inverted: false
        lidar_rear: # spinning lidar
          topic: '/bot_sensor/lidar_rear/laser_scan'
          intrinsics:
            range: [0.05, 20.0] # [min, max]
            fov: [0.0, 2.26893, 4.01426, 6.283185307179586] # [from to from to]
          extrinsics:
            xyz: [-0.5195, -0.2970, 0.2715]
            yaw: -2.386194490185
            inverted: false
        lidar_front_sor: # spinning lidar
          topic: '/bot_sensor/lidar_front/sor_laser_scan'
          intrinsics:
            range: [0.05, 20.0] # [min, max]
            fov: [0.0, 2.26893, 4.01426, 6.283185307179586] # [from to from to]
          extrinsics:
            xyz: [0.5195, 0.2970, 0.2715]
            yaw: 0.785398163
            inverted: false
        lidar_rear_sor: # spinning lidar
          topic: '/bot_sensor/lidar_rear/sor_laser_scan'
          intrinsics:
            range: [0.05, 20.0] # [min, max]                                                                                                                                                                       
            fov: [0.0, 2.26893, 4.01426, 6.283185307179586] # [from to from to]                                                                                                                                     
          extrinsics:                                                                                                                                                                                              
            xyz: [-0.5195, -0.2970, 0.2715]                                                                                                                                                                        
            yaw: -2.386194490185                                                                                                                                                                                
            inverted: false                                                                                                                                                                                        
        virtual_sensor:                                                                                                                                                                                            
          topic: '/jass/virtual_sensor/virtual_sensor'                                                                                                                                                             
          intrinsics:                                                                                                                                                                                            
            range: [0.2, 15.0] # [min, max]                                                                                                                                                                        
          extrinsics:                                                                                                                                                                                             
            xyz: [0.0, 0.0, 0.21]                                                                                                                                                                                  
            yaw: 0.0                                                                                                                                                                                               
                                                                                                                                                                                                                   
 robot.yaml" 79L, 2781B                                                                                                                                                                                           
